apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sensu-go.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sensu-go.name" . }}
    helm.sh/chart: {{ include "sensu-go.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sensu-go.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sensu-go.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: sensu-storage
          persistentVolumeClaim:
            claimName: sensu-claim
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "sh"
            - "-c"
            - "sensu-backend start"
          ports:
            {{ range $item := .Values.backendPorts }}
            - name: {{ $item.name }}
              containerPort: {{ $item.value }}
              protocol: TCP
            {{ end }}
          volumeMounts:
            - mountPath: /var/lib/sensu
              name: sensu-storage
          livenessProbe:
            httpGet:
              path: /
              port: dashboard
          readinessProbe:
            httpGet:
              path: /
              port: dashboard
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
