apiVersion: v1
kind: Service
metadata:
  name: {{ include "sensu-go.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sensu-go.name" . }}
    helm.sh/chart: {{ include "sensu-go.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{ range $item := .Values.backendPorts }}
    - port: {{ $item.value }}
      targetPort: {{ $item.value }}
      protocol: TCP
      name: {{ $item.name }}
    {{ end }}
  selector:
    app.kubernetes.io/name: {{ include "sensu-go.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
